# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1

jobs:
  dockerPush:
    working_directory: ~/app
    docker:
      - image: nephosolutions/docker:latest
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            cd labs/docker
            IMAGE_ACCOUNT=$DOCKER_LOGIN make release
            docker login -u $DOCKER_LOGIN -p $DOCKER_PWD
            IMAGE_ACCOUNT=$DOCKER_LOGIN make pushAll
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  docker:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
      - dockerPush
